In [1]:
import numpy as np
import tensorflow as tf

In [5]:
# Simple RNN
X = []
Y = []
for i in range(6):
    lst = list(range(i,i+4))
    
    X.append(list(map(lambda c: [c/10], lst)))
    
    Y.append((i+4)/10)
    
X = np.array(X)
Y = np.array(Y)

for i in range(len(X)):
    print(X[i], Y[i])

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 0.4
[[0.1]
 [0.2]
 [0.3]
 [0.4]] 0.5
[[0.2]
 [0.3]
 [0.4]
 [0.5]] 0.6
[[0.3]
 [0.4]
 [0.5]
 [0.6]] 0.7
[[0.4]
 [0.5]
 [0.6]
 [0.7]] 0.8
[[0.5]
 [0.6]
 [0.7]
 [0.8]] 0.9


In [4]:
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units=10, return_sequences=False, input_shape=[4,1]),
    tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam', loss='mse')
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 10)                120       
                                                                 
 dense (Dense)               (None, 1)                 11        
                                                                 
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.fit(X, Y, epochs=100, verbose=0)
print(model.predict(X))

1/1 [==============================] - 0s 9ms/step
[[0.46510458]
 [0.5602075 ]
 [0.64062387]
 [0.7050751 ]
 [0.7553734 ]
 [0.7933254 ]]


In [10]:
print(model.predict(np.array([[[0.6],[0.7],[0.8],[0.9]]])))

1/1 [==============================] - 0s 11ms/step
[[0.8200982]]


In [ ]:
# LSTM
X=[]
Y=[]
for i in range(3000):
    